// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/api/create.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/pricing.tsx";
import * as $5 from "./routes/shipping.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Footer.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Hero.tsx";
import * as $$4 from "./islands/ShippingPage.tsx";
import * as $$5 from "./islands/pricingcomponent.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/api/create.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/pricing.tsx": $4,
    "./routes/shipping.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Footer.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Hero.tsx": $$3,
    "./islands/ShippingPage.tsx": $$4,
    "./islands/pricingcomponent.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
