export const farnsworthBio = 'Professor Hubert J. Farnsworth, a luminary of unparalleled intellect, was born on the cusp of the 29th century, in the year 2841. A man shrouded in enigmatic brilliance, he became a prominent figure in the realm of futuristic science and innovation. Throughout his life, he carved an indelible mark on the scientific landscape, captivating generations with his cutting-edge discoveries and eccentric personality.\n' +
    '\n' +
    'From a tender age, Farnsworth exhibited an insatiable curiosity for the cosmos, continually seeking to unravel its mysteries. Raised in the outskirts of the illustrious New New York, his upbringing in the bustling metropolis sowed the seeds of scientific curiosity that would flourish into greatness.\n' +
    '\n' +
    'Farnsworth\'s academic journey took him to Mars University, where he honed his intellect across a plethora of disciplines. A voracious learner, he displayed prodigious talents in quantum physics, temporal mechanics, and unorthodox engineering. His genius earned him accolades, including the prestigious Wernstrom Award, establishing his reputation as a rising star in the scientific community.\n' +
    '\n' +
    'An entrepreneurial spirit fueled Farnsworth\'s ambition, leading him to found the renowned intergalactic delivery company, Planet Express, in the year 2961. The venture aimed not only to finance his research but also to indulge his ever-present thirst for exploration. Farnsworth\'s crew, a motley assembly of individuals, embarked on daring expeditions, traversing the farthest reaches of the universe, all in the pursuit of delivering packages to the remotest corners of inhabited space.\n' +
    '\n' +
    'Throughout his illustrious career, Farnsworth\'s inventive mind birthed a myriad of wondrous gadgets, each a testament to his brilliance. Among these marvels were the Smelloscope, a device that discerned odors from vast distances; the Finglonger, an extendable mechanical finger to access elusive objects; and the ever-curious What-If Machine, capable of simulating fantastical scenarios.\n' +
    '\n' +
    'In addition to his technical prowess, Farnsworth exhibited an idiosyncratic nature that endeared him to colleagues and acquaintances alike. His animated enthusiasm and peculiar humor enlivened even the most mundane moments, making him an unmistakable personality in the scientific community.\n' +
    '\n' +
    'Despite the countless accomplishments and adventures, the passage of time eventually caught up with the esteemed professor. In the later stages of his life, he began to contemplate the legacy he would leave behind. Nevertheless, his unyielding passion for science persisted, driving him to explore new frontiers and embrace every opportunity for innovation.\n' +
    '\n' +
    'The tale of Professor Hubert J. Farnsworth, a man of unmatched intellect, remains an enduring inspiration within the annals of futuristic science. As the universe unfolds and new discoveries await, his legacy continues to serve as a guiding light for aspiring scientists and adventurers, forever etched in the vast cosmos of the 31st century.'